### ISSUE TITLE
v3.12.1 on external CI/CD - ReferenceError: crypto is not defined

### ISSUE THREAD

**Issue by b-tuma** [cloudflare/wrangler-action#329]
Hi,

I have a Gitea action runner using [docker://ghcr.io/catthehacker/ubuntu:act-latest](https://github.com/catthehacker/docker_images/pkgs/container/ubuntu) that fails when running **wrangler-action@v3.12.1** with the following message:

```
2024-11-19T20:12:18.2339725Z file:///run/act/actions/https---github.com-cloudflare-wrangler-action@v3/dist/index.mjs:33086
2024-11-19T20:12:18.2340203Z     WRANGLER_OUTPUT_DIR: `${(0,external_path_.join)((0,external_os_.tmpdir)(), `wranglerArtifacts-${crypto.randomUUID()}`)}`,
2024-11-19T20:12:18.2340386Z                                                                                                     ^
2024-11-19T20:12:18.2340556Z 
2024-11-19T20:12:18.2340696Z ReferenceError: crypto is not defined
2024-11-19T20:12:18.2340848Z     at file:///run/act/actions/https---github.com-cloudflare-wrangler-action@v3/dist/index.mjs:33086:101
2024-11-19T20:12:18.2341007Z     at file:///run/act/actions/https---github.com-cloudflare-wrangler-action@v3/dist/index.mjs:33376:3
2024-11-19T20:12:18.2341175Z     at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
2024-11-19T20:12:18.2341327Z     at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
2024-11-19T20:12:18.2341493Z     at async loadESM (node:internal/process/esm_loader:34:7)
2024-11-19T20:12:18.2341699Z     at async handleMainPromise (node:internal/modules/run_main:106:12)
2024-11-19T20:12:18.2341897Z 
2024-11-19T20:12:18.2342086Z Node.js v18.20.4
2024-11-19T20:12:18.2494544Z exitcode '1': failure
``` 

Rolling back to **v3.12.0** solved the issue, so I assume this is related to the new crypto addition on #318.

**Comment by jahands** [comment]
Hi!

This Action needs to run using Node 20, as specified in [action.yml](https://github.com/cloudflare/wrangler-action/blob/main/action.yml#L8). It looks like Gitea (or the image you're using) are not respecting this value, and instead running it with Node 18.

I would recommend raising this either on the Gitea repo, or the repo for the image you're using.

Sorry for the inconvenience.

**Comment by alvitali** [comment]
hey @b-tuma, did you ever find a workaround to this? didn't find anything on the gitea repo, what did you end up doing?

**Comment by b-tuma** [comment]
Hi @alvitali, I stayed on `https://github.com/cloudflare/wrangler-action@v3.12.0` and haven't looked again at this issue, but if you end up figuring it out, let me know ;)

**Comment by alvitali** [comment]
thanks, that was my temporary solution as well for now ^^ i'll let you know if i find a proper fix! :)

**Comment by fresh2dev** [comment]
Here is an image using node20 that worked well for me:

```
"node20:docker://docker.io/gitea/runner-images:ubuntu-latest-slim"
```
